cart/urls.py
from django.urls import path
from .views import  *

app_name = "cart"
urlpatterns = [
    

    path('',view_cart, name='cart_list'),



    path('delete/<int:id>/',remove_from_cart, name='remove_from_cart'),

    


    path('get-delivery/<str:region>/',get_delivery, name='get_delivery'),

    path('empty/',empty_cart, name='empty_cart'),
    
    path('checkout/',checkout, name='checkout'),

    path('add_to_cart/<int:product_id>/',add_to_cart, name='add_to_cart'),

    path('orders/',orders_list, name='orders_list'),
    path('orders/<str:id>/',order_details, name='order_details'),
    path('orders/<str:id>/received/',received_order, name='received_order'),
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
 
from django.conf import settings
from django.conf.urls.static import static

from cart import views

handler404 = 'users.views.custom_404'


admin.site.index_title = 'PetsNClaws'
admin.site.site_title = 'Admin Panel'
admin.site.site_header = 'PetsNClaws Admin'
admin.site.site_url="http://petsnclaws.com"

from users.views import custom_404
urlpatterns = [
    path('admin/', admin.site.urls),

    path("cart/", include("cart.urls")),
    path("users/", include("users.urls")),
    path("", include("home.urls")),


]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
 
from django.conf import settings
from django.conf.urls.static import static

from cart import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path("cart/", include("cart.urls")),
    path("users/", include("users.urls")),
    path("", include("home.urls")),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import  *

app_name = "home"
urlpatterns = [
    

    path('',homepage, name='home'),
    path('products/',productsPage, name='products'),
    path('search_products/',searchProducts, name='search_products'),
    path('contact-us/',contactUs, name='contactUs'),


    path('product/<int:pk>/',productDetails, name='details'),



    
]

users/urls.py
from django.urls import path
from .views import  *

app_name = "users"
urlpatterns = [
    
    path('logout/',user_logout, name='logout'),

    path('login/',user_login, name='login'),

    path('register/',user_register, name='register'),

]

home/models.py
from django.db import models

# Create your models here.

from django_resized import ResizedImageField

from datetime import datetime


def uploadedform(object,filename):
    try:
        import pathlib
        file_extension = pathlib.Path(filename).suffix

        timestamp = datetime.now().timestamp()

        return f'gallery/{timestamp}{file_extension}'

    except Exception as e:
        print(f"error uploading gallery,{e}")

def uploadbrand(object,filename):
    try:
        import pathlib
        file_extension = pathlib.Path(filename).suffix
        timestamp = datetime.now().timestamp()
        return f'brands/{timestamp}{file_extension}'

    except Exception as e:
        print(f"error uploading brand,{e}")


class Gallery(models.Model):
    name=models.CharField(max_length=100,null=True,blank=True)
    image = ResizedImageField(upload_to=uploadedform)

    def __str__(self):
        if(self.name):
            return self.name
        else:
            return  f"{self.pk}"
    class Meta:
        verbose_name = "Gallery"
        verbose_name_plural = "Gallery"


class Brands(models.Model):
    name=models.CharField(max_length=100,null=True,blank=True)
    image = ResizedImageField(upload_to=uploadbrand)
    
    def __str__(self):
        if(self.name):
            return self.name
        else:
            return  f"{self.pk}"
    class Meta:
        verbose_name = "Brands"
        verbose_name_plural = "Brands"


class ContactUs(models.Model):
    name=models.CharField(max_length=50)
    email=models.CharField(max_length=100)
    subject=models.CharField(max_length=50)
    message=models.TextField()
    def __str__(self):
        return self.name 
    class Meta:
        verbose_name = "Contact Us"
        verbose_name_plural = "Contact Us"
        
        
        
class SocialLinks(models.Model):
    icon = models.CharField(max_length=100)
    color = models.CharField(max_length=100, null=True, blank=True)
    link = models.TextField()

    def __str__(self):
        return self.icon 
    class Meta:
        verbose_name_plural = "Social Links"

home/views.py
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from cart.models import *
from cart.views import send_email
from settings.models import Settings
from .models import *
import django_filters

def homepage(request):
     
    products = Product.objects.filter(status__name="suggested").order_by('rank')

    gallery=Gallery.objects.all()
    brands=Brands.objects.all()

    cart = request.session.get('cart', [])

    sale_products=Product.objects.filter(status__name="promotion").order_by('rank')

    cats=Category.objects.all()

    total_qty=0
    for item in cart:
        total_qty+=item['qty']

    context = {
        'sale_products':sale_products,
        'products': products,
        'gallery':gallery,
        'brands':brands,
        "cart":cart,
        'total_qty':total_qty,
        'cats':cats
    }
    return render(request, 'home.html',context)



class ProductFilter(django_filters.FilterSet):
    category = django_filters.CharFilter(field_name='category__name', lookup_expr='exact')
    brand= django_filters.CharFilter(field_name='brand__name', lookup_expr='exact')
    sub_category= django_filters.CharFilter(field_name='sub_category__name', lookup_expr='exact')
    class Meta:
        model = Product
        fields = ['category','brand']
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
def productsPage(request):

    # categories = Category.objects.prefetch_related('subcategory_set').all()
    # print(categories)
    categories=Category.objects.all()
    # for cat in categories:
    #     for subcategory in category.subcategory_set.all

    sub_cat=SubCategory.objects.all()

    items_per_page = 12

    page= request.GET.get('page', 1)
     
    queryset=Product.objects.filter(status__listed=True).order_by('rank')
    
    filter = ProductFilter(request.GET,queryset=queryset)

    paginator = Paginator(filter.qs, items_per_page)

    try:
        paginated_items = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver the first page
        paginated_items = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g., 9999), deliver the last page
        paginated_items = paginator.page(paginator.num_pages)


    cart = request.session.get('cart', [])

    total_qty=0
    for item in cart:
        total_qty+=item['qty']

    
    context = {
        'products': paginated_items,
        "cart":cart,
        'total_qty':total_qty,
        "categories":categories,
        'paginated_items': paginated_items,
        'sub_cat':sub_cat
    }
    return render(request, 'products.html',context)

def contactUs(request):
    if request.method == 'POST':
        fullname = request.POST['fullname']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']
        contact_us=ContactUs.objects.create(
            name=fullname,
            email=email,
            subject=subject,
            message=message
        )
        try:
            settings=Settings.objects.get()
            html_message=f"""
                <h3>Hello Dear, <br> 
                You have a new message from {fullname} having the email: {email}<br>
                message subject:{subject} <br>
                Message content:{message}<br>
                <a style="color:#83B641" href="{settings.admin_link}/home/contactus/{contact_us.pk}/change/" >Click here</a> for more details
                </h3>
            """
            send_email(f"New Message from {fullname}",html_message,settings.reciever_email)
        except Exception as e:
            print(f"email didnt send,{e}")

        context={
            "success":'success',
        }
        return JsonResponse(context)
    cart = request.session.get('cart', [])

    total_qty=0
    for item in cart:
        total_qty+=item['qty']

    context = {
        "cart":cart,
        'total_qty':total_qty
    }

    return render(request, 'contact_us.html',context)


from django.db.models import Q
def searchProducts(request):
    if request.method == 'POST':
        query = request.POST['query']

        products = Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query)).order_by('rank')

        cart = request.session.get('cart', [])
        total_qty=0
        for item in cart:
            total_qty+=item['qty']

        context = {
            'total_qty':total_qty,
            'products': products,
            "cart":cart,
            "query":query,
        }

        return render(request, 'search_products.html',context)
    
def productDetails(request,pk):


    cart = request.session.get('cart', [])
    total_qty=0
    for item in cart:
        total_qty+=item['qty']

    product=Product.objects.get(pk=pk)
    settings=Settings.objects.get()

    description=product.description.split("\n")
    context = {
        'total_qty':total_qty,
        "cart":cart,
        'product':product,
        'currency':settings.currency,
        'description':description

    }

    return render(request, 'product_details.html',context)
    # for category in categories:
    #     products = Product.objects.filter(status__listed=True,category=category)
    #     if(products.count()> 0):
    #         products_list[category.name]=products

home/templates/contact_us.html
{% extends 'layout.html' %}



{% block title %} Contact Us {% endblock %}


{% block links1 %} 
<li class="nav-item ">
  <a class="nav-link " href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
  </li>

  <li class="nav-item">
  <a class="nav-link " href="{% url 'home:products' %}">Products</a>
  </li>
  {% comment %} <li class="nav-item">
  <a class="nav-link" href="/shop/customize">customize</a>
  </li>
{% endcomment %}
  <li class="nav-item">
  <a class="nav-link active" href="{% url 'home:contactUs' %}">Contact Us</a>
  </li>
  
{% endblock %}

{% block links %} 
<li class="nav-item ">
  <a class="nav-link " href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
  </li>

  <li class="nav-item">
  <a class="nav-link " href="{% url 'home:products' %}">Products</a>
  </li>
  {% comment %} <li class="nav-item">
  <a class="nav-link" href="/shop/customize">customize</a>
  </li>
{% endcomment %}
  <li class="nav-item">
  <a class="nav-link active" href="{% url 'home:contactUs' %}">Contact Us</a>
  </li>
  
{% endblock %}



{% block main %} 

<div class="container-md-fluid container-lg">
  <h2 class="title-sell">Contact Us</h2>


 <div class="row no-gutters mb-5">

    <div class="col-md-6">
       <div class="contact-wrap w-100 p-lg-5 p-4">
         <div class="alert alert-danger hidden" id="alert_errors">
         </div>
          <div id="form-message-warning" class="mb-4"></div> 
          <form  id="contactForm" name="contactForm" class="contactForm">
             <div class="row">
                <div class="col-md-6">
                   <div class="form-group">
                      <label class="label" for="name">Fullname</label>
                      <input type="text" class="form-control" name="name" id="name" placeholder="Fullname">
                   </div>
                </div>
                <div class="col-md-6">  
                   <div class="form-group"> 
                      <label class="label" for="email">Email</label>
                      <input type="email" class="form-control" name="email" id="email" placeholder="Email">
                      <span class="text-danger" id="emailalert"></span>
                   </div>
                </div>
                <div class="col-md-12">
                   <div class="form-group">
                      <label class="label" for="subject">Subject</label>
                      <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject">
                   </div>
                </div>
                <div class="col-md-12">
                   <div class="form-group">
                      <label class="label " for="#">Message</label>
                      <textarea name="message" class="form-control" id="message" cols="30" rows="4" placeholder="Message"></textarea>
                   </div>
                </div>
                <div class="col-md-12 mt-2">
                   <div class="form-group text-center">

                     <button type="button"  class="btn btn-login w-50" id="btnSend">
                        Send
                    </button>

                   </div>
                </div>
             </div>
          </form>
       </div>
    </div>
    <div class="col-md-6" style="height:45vh">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d848029.5583045399!2d34.89068480076072!3d33.873799753099895!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x151ef12c998b5d19%3A0xc65ebd7d359417ad!2sPets%20N%20Claws!5e0!3m2!1sen!2slb!4v1694715402386!5m2!1sen!2slb" width="500" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>    </div>
 </div>
</div>
</div>


<script src="/assets/js/contact_us.js"></script>

{% endblock %}

home/templates/layout.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js">  <![endif]-->
<html lang="en">
    <head>
        
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-GXMBL7V19N"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-GXMBL7V19N');
</script>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>
          PetsNClaws | 
          {% block title %}
          {% endblock %}
        
        </title>


        <meta name="viewport" content="width=device-width, initial-scale=1">


        <meta name="description"
        content="Discover the ultimate pet store for all your furry friends! 
                 PetsNclaws offers a wide range of pet products and expert grooming services.
                 Spoil your pets with top-quality care and supplies." >


        <meta name="theme-color" content="#83B641">

        <meta property="og:title" content="PetsNclaws - Your Pet's Paradise">

        <link rel="icon" type="image/x-icon" href="/assets/favicon.ico">



        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">



        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  


        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,900,900i" rel="stylesheet">


        <link rel="stylesheet" href="/assets/css/cart.css">
        <link rel="stylesheet" href="/assets/css/menu.css">
        
        <link rel="stylesheet"  href="/assets/css/ourwork.css">

        <link rel="stylesheet" href="/assets/css/shop-home.css">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        

        <div class="notify text-center" id="notify">
            <div class="popup">
              <span class="popuptext alert bg-black text-green p-md-3 p-2" id="myPopup">
                <i class="fas fa-check-circle text-green"></i>  Product successfully added to your cart
              </span>
            </div>
        </div>
        

        <a id="whatsapp" class="d-md-block" href="https://wa.me/{{settings.phone}}" target="_blank"></a>

        {% comment %} <a id="button"></a> {% endcomment %}
        
  
        <div id="myDiv" ><!-- style="display:none;"-->

            <div class="overlay"></div>
              <div class="utility-nav d-block d-md-block " >
          
                      <p class="text-center text-top">Payment in USD and LBP,Rate is determined upon delivery</p>
              
              </div>

           

        <nav class="navbar navbar-expand-lg navbar-light bg-light main-menu" style="box-shadow:none">

            <div class="container-fluid">
                <button type="button" id="sidebarCollapse" class="btn btn-link d-block d-lg-none" aria-label="menu">
                <i class="fas fa-bars text-dark icon-single"></i>
                </button>
                <a class="navbar-brand" href="{% url 'home:home' %}" >
                  <div class="row align-items-center">
                    <div class="col-md-4 col-4" style="padding-right: 0px;">
                          <!-- Logo -->
                        <img src="/assets/logo-no_bg.png" alt="Logo" class="rounded-logo">
                    </div>
                    <div class="col-md-3 col-3 ">
                      <!-- Company Name -->
                      <h1 >
                          <span class="style1">Pets</span><span class="style2">N</span><span class="style3">Claws</span>
                      </h1> 
                    </div>
                  </div>
                </a>
                <ul class="navbar-nav ml-auto d-block d-lg-none">
                  <li class="nav-item" >
                      <a class="btn btn-link" href="/cart"><i class="fas fa-shopping-cart icon-single"></i>
                        <span class="badge badge-danger item-nb cart_qty">
                          {{total_qty}}
                        </span>
                      </a>
                  </li>
                </ul>
                <div class="collapse navbar-collapse">
                  <form class="form-inline  my-lg-0 mx-auto" action="/search_products/" method="POST">
                    {% csrf_token %}
                      <input class="form-control text-search" value="{{query}}" type="text" name="query" placeholder="Search Products ..." aria-label="Search">
                      <button class="btn search-btn "  type="submit" aria-label="search"><i class="fas fa-search"></i></button>
                  </form>
                  <ul class="navbar-nav">
                      <li class="nav-item">
                        <a class="btn btn-link" href="/cart">
                          <i class="fas fa-shopping-cart icon-single"></i>
                          <span class="badge badge-danger item-nb cart_qty">
                           {{total_qty}}
                          </span>
                        </a>
                      </li>
                      <li class="nav-item ml-md-3">
                        {% if not user.is_authenticated %}
                        <a class="btn btn-login"  href="{% url 'users:login' %}"><i class="fas fa-user-circle mr-1"></i>login</a>
                        {% else %}
                        <a class="btn btn-login"  href="{% url 'users:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i></i>logout</a>
                        {% endif %}
                      </li>
                  </ul>
                </div>
            </div>



          </nav>

          <nav class="navbar navbar-expand-lg navbar-light bg-light sub-menu">
            <div class="container">
                <div class="collapse navbar-collapse" id="navbar">
                  <ul class="nav navbar-nav navbar-nav mx-auto ">
                   
                    {% block links %}
                    {% endblock %}

                  </ul>
                </div>
            </div>
          </nav>
      
          <div class="search-bar d-block d-lg-none">
            <div class="container">
                <div class="row">
                  <div class="col-12">
                    <form class="form-inline my-2 my-lg-0 mx-auto" action="/search_products/" method="POST">
                      {% csrf_token %}
                        <input class="form-control" type="text" value="{{query}}" name="query" placeholder="search products ..." aria-label="Search">
                        <button class="btn search-btn" type="submit" aria-label="search"><i class="fas fa-search"></i></button>
                      </form>
                  </div>
                </div>
            </div>
          </div>
          <!-- Sidebar -->
          <nav id="sidebar">
            <div class="sidebar-header">
                <div class="container">
                  <div class="row align-items-center">
                      <div class="col-10 pl-0">

                        {% if not user.is_authenticated %}
                        <a class="btn btn-login"  href="{% url 'users:login' %}"><i class="fas fa-user-circle mr-1"></i>login</a>
                        {% else %}
                        <a class="btn btn-login"  href="{% url 'users:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i></i>logout</a>
                        {% endif %}
                        
                      </div>
                      <div class="col-2 text-left">
                        <button type="button" id="sidebarCollapseX" class="btn btn-link" aria-label="close">
                          <i class="fas fa-times icon-single text-dark"></i>
                        </button>
                      </div>
                  </div>
                </div>
            </div>
            <ul class="list-unstyled components links">
                           {% block links1 %}
                    {% endblock %}
            </ul>
          </nav>


</div><!-- end myDiv -->



{% block main %}
{% endblock %}
<br>


<div class="text-center  p-2 bg-green foot-shadow" >
          
  <h5 class=" text-light">
    Need products in massive quantities?<a href="/contact-us/" class="text-black reach-us "> Contact us</a> today for unbeatable deals!
  </h5>

</div>
<!-- Start Contact info -->
<div class="contact-imfo-box ">
    <div class="container">
      <div class="row justify-content-lg-center">
        <div class="col-md-4 col-lg-3 form-group  ">
          <i class="fa fa-phone  "></i>
          <div class="overflow-hidden" >
            <h4 >Phone</h4>
            <p class="lead ">
              {{settings.phone}}
            </p>
          </div>
        </div>
        <div class="col-md-4  col-lg-3 form-group  " >
          <i class="fa fa-instagram  "></i>
          <div class="overflow-hidden">
            <h4>Instagram</h4>
            <p class="lead">
              {{settings.instagram}}
            </p>
          </div>
        </div>
        <div class="col-md-4   col-lg-3 form-group  ">
          <i class="fa fa-map-marker  "></i>
          <div class="overflow-hidden">
            <h4>Location</h4>
            <p class="lead">
              Saida-Hlalieh
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End Contact info -->
  
  
  
    <!-- Start Footer -->
      <footer class="footer-area bg-f">
          <div class="container">
              <div class="row justify-content-center">
                  <div class="col-lg-4 col-md-6">
                      <h3 >About Us</h3>
                      <p>
                        Welcome to our premier online pet store, where your furry friends’ happiness is our top priority.
                        At our virtual haven for pets and pet owners, we offer a wide selection of high-quality products to cater to all your pet’s needs. 
                        Whether you have a playful pup, a finicky feline, or a feathered friend, 
                        you’ll find everything from nutritious pet food and stylish accessories to cozy beds and interactive toys.
                      </p>
            </p>
                  </div>
                  {% comment %} <div class="col-lg-3 col-md-6">
                      <h3 class=" ">openings</h3>
                      <p><span class="text-color">Monday: </span>2:00 Am - 8:00 PM</p>
                      <p><span class="text-color">Tue-Wed :</span> 2:00 Am - 8:00 PM</p>
                      <p><span class="text-color">Thu :</span> 2:00 Am - 8:00 PM</p>
                      <p><span class="text-color">Fri </span>closed</p>
                      <p><span class="text-color">Sat-Sun :</span> 2:00 Am - 8:00 PM</p>
                  </div> {% endcomment %}
                  <div class="col-lg-4 col-md-3  ">
                      <h3 >contact us</h3>
                      <p class="lead">  <i class="fa fa-map-marker green-icon  "></i> Saida-Hlalieh </p>
                      <p class="lead"><i class="fa fa-phone  green-icon"></i> {{settings.phone}}</p>
                      <p class="lead"> <i class="fas fa-envelope green-icon"></i> {{settings.email}}</p>
                  </div>
                  <div class="col-lg-4 col-md-3">
                      <h3 class=" ">follow</h3>
  
                      <ul class="list-inline f-social  ">
                          {% for link  in links  %}
                            <li class ="list-inline-item"><a href="{{link.link}}" target="_blank"><i class="{{link.icon}}" aria-hidden="true"></i></a></li>
                          {% endfor %}                    


  
                      </ul>
                  </div>
              </div>
          </div>


          <div class="copyright">
              <div class="container">
                  <div class="row justify-content-center">
  
                      <div class="col-lg-12">
                          <p class="company-name text-center"> All Rights Reserved &copy; 2023 
                             By<a href="https://mostafanawam.github.io/" target="_blank" class="signiture"> Mostafa Nawam</a></p>
                      </div>
                  </div>
              </div>
          </div>
  
      </footer>





      <script src="/assets/js/ourwork.js"></script>

      <script src="/assets/js/shop-home.js"></script> 
      <script src="/assets/js/add_to_cart.js"></script>

home/templates/product_details.html
{% extends 'layout.html' %}



{% block title %} Contact Us {% endblock %}


{% block links1 %} 
<li class="nav-item ">
  <a class="nav-link " href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
  </li>

  <li class="nav-item">
  <a class="nav-link " href="{% url 'home:products' %}">Products</a>
  </li>
  {% comment %} <li class="nav-item">
  <a class="nav-link" href="/shop/customize">customize</a>
  </li>
{% endcomment %}
  <li class="nav-item">
  <a class="nav-link active" href="{% url 'home:contactUs' %}">Contact Us</a>
  </li>
  
{% endblock %}

{% block links %} 
<li class="nav-item ">
  <a class="nav-link " href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
  </li>

  <li class="nav-item">
  <a class="nav-link " href="{% url 'home:products' %}">Products</a>
  </li>
  {% comment %} <li class="nav-item">
  <a class="nav-link" href="/shop/customize">customize</a>
  </li>
{% endcomment %}
  <li class="nav-item">
  <a class="nav-link" href="{% url 'home:contactUs' %}">Contact Us</a>
  </li>
  
{% endblock %}



{% block main %} 
<div class="container mt-4 p-4">




<div class="about-section-box">
    <div class="container-fluid">
        <div class="row ">
            <div class="col-lg-6 col-md-6 col-sm-12">
                <img src="{{ product.image.url }}"  class="prod-details-img rounded form-group  " alt="prod_{{product.name}}">
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="inner-column mt-md-4 ">
                    <h3 >
                     {{product.name}}
                    </h3>
                    {% if product.brand %}
                    <p class="text-muted p-0 mb-0 mt-0">
                      by {{product.brand.name}}
                    </p>
                    {% endif %}
                    {% if product.old_price %}

                    <h4 style="display: inline-block;  opacity: 0.5;">
                      <s class="">{{settings.currency}}{{ product.old_price }}</s>

                    </h4>
                    {% endif %}
                      <h3 class="green"  style="display: inline-block;">
                      {{settings.currency}}{{ product.price }}
                    </h3>


                    <ul >
                      {% for desc in  description %}
                        {% if desc %}
                          <li class="h5">{{desc}}</li>
                        {% endif %}
                      
                      {% endfor %}
                    </ul>

                    <div class="text-center mt-4">
                        {% csrf_token %}
                        {% if product.stock > 0 %}
                          <button  class="add_to_cart btn btn-sm btn-login w-100 p-2" id="btn_{{product.id}}"  data-product-id="{{ product.id }}" >
                            Add to Cart <i class="fas fa-cart-plus"></i>
                          </button>
                        {% else %}
                            <button  class="add_to_cart btn btn-sm  btn-disabled  w-100 p-2" id="btn_{{product.id}}"   data-product-id="{{ product.id }}" disabled >
                              out of stock
                            </button>
                        {% endif %}
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
</div>


{% endblock %}