cart/urls.py
from django.urls import path
from .views import  *

app_name = "cart"
urlpatterns = [
    

    path('',view_cart, name='cart_list'),



    path('delete/<int:id>/',remove_from_cart, name='remove_from_cart'),

    


    path('get-delivery/<str:region>/',get_delivery, name='get_delivery'),

    path('empty/',empty_cart, name='empty_cart'),
    
    path('checkout/',checkout, name='checkout'),

    path('add_to_cart/<int:product_id>/',add_to_cart, name='add_to_cart'),

    path('orders/',orders_list, name='orders_list'),
    path('orders/<str:id>/',order_details, name='order_details'),
    path('orders/<str:id>/received/',received_order, name='received_order'),
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
 
from django.conf import settings
from django.conf.urls.static import static

from cart import views

handler404 = 'users.views.custom_404'


admin.site.index_title = 'PetsNClaws'
admin.site.site_title = 'Admin Panel'
admin.site.site_header = 'PetsNClaws Admin'
admin.site.site_url="http://petsnclaws.com"

from users.views import custom_404
urlpatterns = [
    path('admin/', admin.site.urls),

    path("cart/", include("cart.urls")),
    path("users/", include("users.urls")),
    path("", include("home.urls")),


]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
 
from django.conf import settings
from django.conf.urls.static import static

from cart import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path("cart/", include("cart.urls")),
    path("users/", include("users.urls")),
    path("", include("home.urls")),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import  *

app_name = "home"
urlpatterns = [
    

    path('',homepage, name='home'),
    path('products/',productsPage, name='products'),
    path('search_products/',searchProducts, name='search_products'),
    path('contact-us/',contactUs, name='contactUs'),


    path('product/<int:pk>/',productDetails, name='details'),



    
]

cart/models.py
from django.db import models
from django_resized import ResizedImageField

from home.models import Brands


# python manage.py dumpdata cart.Status --output cart/fixtures/Status.test.json
class Status(models.Model):
    name = models.CharField(max_length=100)
    listed=models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Status"
        verbose_name_plural = "Status"


def uploadCat(object,filename):
    try:
        import pathlib
        file_extension = pathlib.Path(filename).suffix
        return f'categories/{object.name}{file_extension}'

    except Exception as e:
        print(f"error uploading id to minio,{e}")

# python manage.py dumpdata cart.Category --output cart/fixtures/Category.static.json
class Category(models.Model):
    name = models.CharField(max_length=100)
    image=ResizedImageField(upload_to=uploadCat,null=True,blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Categories"
        verbose_name_plural = "Categories"


# python manage.py dumpdata cart.SubCategory --output cart/fixtures/SubCategory.static.json
class SubCategory(models.Model):
    category=models.ForeignKey(
        Category,
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name} - {self.category.name}"

    class Meta:
        verbose_name = "Sub Category"
        verbose_name_plural = "Sub Category"



def uploadedform(object,filename):
    try:
        import pathlib
        file_extension = pathlib.Path(filename).suffix
        return f'products/{object.name}/{object.name}{file_extension}'

    except Exception as e:
        print(f"error uploading id to minio,{e}")
        
TEXT_COLOR = [
        ('green', 'green'),
        ('text-black', 'text-black'),
        ('text-white', 'text-white'),
]

# python3 manage.py dumpdata cart.Product --output cart/fixtures/Product.test-3.json
class Product(models.Model):
    name = models.CharField(max_length=100,unique=True)
    description = models.TextField(null=True,blank=True)
    price = models.DecimalField(null=True,blank=True,max_digits=5, decimal_places=2)
    old_price = models.DecimalField(null=True,blank=True,max_digits=5, decimal_places=2)
    category = models.ForeignKey(
        Category, 
        on_delete=models.PROTECT,
        null=True,blank=True
    )
    sub_category = models.ForeignKey(
        SubCategory, 
        on_delete=models.PROTECT,
        null=True,blank=True
    )
    image=ResizedImageField(upload_to=uploadedform)
    status=models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        default=1
    )
    stock = models.IntegerField()
    color=models.CharField(max_length=50, choices=TEXT_COLOR,default='text-black')
    brand=models.ForeignKey(
        Brands,
        on_delete=models.PROTECT,
        null=True,blank=True
    )
    rank=models.IntegerField(default=100)
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Products"
        verbose_name_plural = "Products"



class Order(models.Model):
    order_id=models.CharField(max_length=15)
    customer = models.ForeignKey(
        "users.Customer", on_delete=models.PROTECT,
    )
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    delivery=models.DecimalField(max_digits=10, decimal_places=2,null=True,blank=True)
    address= models.ForeignKey(
        "users.Address", on_delete=models.PROTECT
    )
    order_date = models.DateTimeField(auto_now_add=True)
    isReceived=models.BooleanField(default=False)
    def __str__(self):
        return f"#{self.order_id}"

class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.PROTECT
    )
    product = models.ForeignKey(
        Product, on_delete=models.PROTECT
    )
    quantity = models.PositiveIntegerField()

cart/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from settings.models import Settings
from users.models import Address, Customer, Regions
from users.tasks import send_email
from .models import Order, OrderItem, Product
from django.http import HttpResponse


def get_delivery(request,region):
    region=Regions.objects.get(name=region)
    context={
        "success":'success',
        "delivery":region.delivery,

    }
    # print(region.delivery)
    return JsonResponse(context)


def orders_list(request):
    if request.user.is_authenticated:

        orders=Order.objects.all().order_by('-order_date')

        context={
            "orders":orders,
        }
        return render(request, 'orders_list.html', context)
    return HttpResponse("you need to be logged in")

def order_details(request, id):
    if request.user.is_authenticated:

        try:
            order=Order.objects.get(order_id=id)
        except:
            return HttpResponse(f"order with id={id} not found")
        items=OrderItem.objects.filter(order=order)

        settings=Settings.objects.get()
        context={
            "order":order,
            "items":items,
            "settings":settings
        }
        return render(request, 'order_details.html', context)
    
    return HttpResponse("you need to be logged in")

def received_order(request, id):

    try:
        order=Order.objects.get(order_id=id)
    except:
        return HttpResponse(f"order with id={id} not found")
    settings=Settings.objects.get()
    instagram=settings.instagram
    if(not order.isReceived):
        order.isReceived=True
        order.save()
        html=f"""<p>Dear Customer,</p>
                    <p>Exciting news! Your pet's treats from PetsNClaws have just arrived. We hope they love them!</p>
                    <p>Share your experience with us by leaving a quick review on our social media platforms. Got a cute pic? Spread the joy on Instagram, mentioning us @{instagram} and using #PetJoy. Your pet might even become a star on our page!</p>
                    <p>Thanks for choosing PetsNClaws. Here's to happy, healthy pets!</p>
                    <p>Best Regards,<br>PetsNClaws Customer Service Team</p>
                    """

        if(order.customer.email):
            email=order.customer.email
        else:
            email=order.customer.user.email
        try:
            send_email(f'PetsNClaws - Order Received',html,email)
        except Exception as e:
            print(f"received_order:email didnt send,{e}")   

    orders=Order.objects.all().order_by('-order_date')
    context={
        "orders":orders,
    }
    return render(request, 'orders_list.html', context)

def add_to_cart(request, product_id):
    product = Product.objects.get(pk=product_id)
    
    if 'cart' not in request.session:
        request.session['cart'] = []
    
    cart = request.session['cart']

    product_found=False
    for item in cart:
        if item['id'] == product_id:
            item['qty'] += 1  # Increment the quantity by 1
            item['total_price']=float(item['qty'])*float(item['price'])
            product_found = True
            break

    if not product_found:
        cart.append({
            'id': product.pk,
            'name': product.name,
            'description': product.description,
            'price': str(product.price),
            'image': product.image.url,
            'qty':1,
            'total_price':str(product.price)
        })
    request.session.modified = True

    total_qty=0
    for item in cart:
        total_qty+=item['qty']
    return HttpResponse(total_qty)

def view_cart(request):
    cart = request.session.get('cart', [])
    total_price = sum(float(item['total_price']) for item in cart)
    
    settings=Settings.objects.get()

    total_qty=0
    for item in cart:
        total_qty+=item['qty']

    context = {
        'total_qty':total_qty,
        'cart': cart,
        'total_price': total_price,
        "settings":settings
    }

    
    return render(request, 'view_cart.html', context)




def empty_cart(request):
    if(request.method == 'POST'):
        if 'cart'  in request.session:
            del request.session['cart']

        return redirect('/cart')

def remove_from_cart(request,id):
    cart = request.session.get('cart', [])

    # Remove the item at the specified index
    del cart[id-1]

    # Update the session with the modified cart
    request.session['cart'] = cart

    return redirect('/cart')


from datetime import datetime
from decimal import Decimal


def checkout(request):
        
    cart = request.session.get('cart', [])
    total_price = sum(float(item['total_price']) for item in cart)
    if(len(cart)==0):
        return redirect("/products/")
    settings=Settings.objects.get()

    if(request.method == 'POST'):
        user=None
        if request.user.is_authenticated:
            user=request.user
            address_type = request.POST.get('type')
            customer=Customer.objects.get(user=request.user)
            if(address_type=="choose"):
                # auth ,select from saved address
                selected_address = request.POST.get('selected_address')
            
                address=Address.objects.get(pk=int(selected_address))

                
                order_id=generate_random_id()
                order=Order.objects.create(
                    total_price=total_price,
                    customer=customer,
                    address=address,
                    order_id=order_id,
                    delivery=address.region.delivery
                )
                for item in cart:
                    product=Product.objects.get(id=item['id'])
                    product.stock=product.stock-item['qty']
                    product.save()
                    OrderItem.objects.create(
                        order=order,
                        product=product,
                        quantity=item['qty'],
                    )
                if 'cart'  in request.session:
                    del request.session['cart']

         

                html_customer=f"""
                    <p>Dear Customer,</p>
                    <p>Thank you for choosing PetsNClaws for your pet's nutritional needs! We are delighted to inform you that your order has been successfully processed and is now on its way.</p>
                    <br>
                    <p>Order Number:{order.order_id}</p>
                    <p>Total:${total_price}</p>
                    <p>You will receive it within 2 to 3 days</p>
                    <br>
                    <p>If you have any questions or concerns about your order, please feel free to contact our customer service team at {settings.email} or {settings.phone}. We are here to assist you!</p>
                    <p>Thank you once again for choosing PetsNClaws for your pet's nutrition. We look forward to being a part of your pet's wellness journey.</p>
                    <p>Best Regards,<br>PetsNClaws Customer Service Team</p>
                    """
            
                try:
                    if(request.user.email):
                        email=request.user.email
                    else:
                        email=customer.email
                    send_email.apply_async(args=(f'PetsNClaws - Order Confirmation',html_customer,email),countdown=120)
                except Exception as e:
                    print(f"email didnt send,{e}")


                try:
                    html=f"""
                    <h3>New Order  from {customer.first_name} {customer.last_name} </h3>
                    <p>Hello Dear,<br> You have new order with id=#{order.order_id} <br>total price={total_price}$<br>Delivery address= {address.region.name},{address.address}</p>
                    <p>For more details <a style="color:red" href='{settings.admin_link}/cart/orders/{order.order_id}/' >click here</a></p>
                    """
                    send_email.delay(f'PetsNClaws - New Order',html,settings.reciever_email)
                except Exception as e:
                    print(f"email didnt send,{e}")


                context={
                    "success":'success',
                    "date": datetime.now().strftime("%b %d, %Y"),
                    "order_id":order_id,
                    "address":f"{address.region.name},{address.address}"
                }
                return JsonResponse(context)
            else:
                # auth but new address
                phone = request.POST['phone']
                region=request.POST['region']
                address=request.POST['address']
                note = request.POST['note']
                region=Regions.objects.get(id=region)

                address=Address.objects.create(
                    region=region,
                    address=address,
                    note=note,
                    phone_number=phone
                ) 
                customer.address.add(address)

                order_id=generate_random_id()
                order=Order.objects.create(
                    total_price=total_price,
                    customer=customer,
                    address=address,
                    order_id=order_id,
                    delivery=region.delivery
                )
                for item in cart:
                    product=Product.objects.get(id=item['id'])
                    product.stock=product.stock-item['qty']
                    product.save()
                    OrderItem.objects.create(
                        order=order,
                        product=product,
                        quantity=item['qty'],
                    )
                if 'cart'  in request.session:
                    del request.session['cart']
                context={
                    "success":'success',
                    "date": datetime.now().strftime("%b %d, %Y"),

cart/templates/order_details.html
{% load replace %}
{% load static %}


<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>
            PetsNClaws | OrderDetails
          
          </title>
          <link rel="icon" type="image/x-icon" href="/assets/favicon.ico">
    
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">

    </head>
    <body>

                <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        
        <div class="container mt-4">
            <h1 class="text-center ">PetsNClaws Order Details</h1>


    

            <div class="row">
                <div class="col-md-4 form-group">
                    <div class="alert alert-primary h-100" role="alert">
                        <h4 class="font-weight-bold">Order Details:</h4>
                        <p >Number: {{order.order_id}}</p>
                        <p >Date: {{order.order_date}}</p>

                    </div>
                </div>

                <div class="col-md-4 form-group">
                    <div class="alert alert-success h-100" role="alert">
                        <h4  class="font-weight-bold">Customer Details:</h4>

                        <p>Name: {{order.customer}}</p>
    
                        <p>
                            Phone:
                            {% if order.address.phone_number %}
                                {{order.address.phone_number}}
                            {% else %}
                                -
                            {% endif %}
                        </p>
                              
                        <p>
                            Email:{% if order.customer.email %}
                              {{order.customer.email }}
                            {% else %}
                                -
                            {% endif %}
                        </p>
                      </div>
                </div>

                <div class="col-md-4 form-group">
                    <div class="alert alert-danger h-100" role="alert">
                        <h4  class="font-weight-bold">Address Details:</h4>


                        <p>Region: {{order.address.region}}</p>
                        <p>Address: {{order.address}}</p>
                        <p>Note:{% if order.address.note %}
                                {{order.address.note}}
                            {% else %}
                                -
                            {% endif %}
                        </p>

                      </div>
                </div>

            </div>

        <br>
         <h4><b>Order Items:</b></h4>
            <table id="myDataTable" class="table table-bordered text-center  table-responsive-sm">
                <thead>
                    <tr>
                        <th class="d-none d-md-block">&nbsp;</th>
                        <th>Product</th>
                        <th>Unit Price</th>
                        <th>Quantity</th>
                        <th>Total Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in items %}
                    <tr>
                        <td class="d-none d-md-block">
                            {% if item.product.image %}
                            <img src="{{ item.product.image.url }}" width="150" height="100" class=" rounded-circle" alt="item_{{product.name}}" class="">
                            {% endif %}
                        </td>
                        <td>
                            {{item.product.name}}
                        </td>
                        <td>
                            {{item.product.price}}
                        </td>
                        <td>
                            {{item.quantity}}
                        </td>
                        <td>

                            ${{item.product.price | multiply:item.quantity}}

                            {% comment %} {{ item.product.price * item.quantity }} {% endcomment %}
                        </td>
                    </tr>
               {% endfor %}
                </tbody>
            </table>


        
            <h4>Net Price &nbsp;&nbsp;= <b>${{order.total_price}}</b></h4>
            <h4>Delivery&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;= <b>${{order.delivery}}</b></h4>

            <h4>Total Price = <b>${{order.total_price | sum:order.delivery}}</b></h4>

        </div>
        


    </body>
</html>

cart/templates/orders_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        PetsNClaws | OrdersList
      
      </title>
      <link rel="icon" type="image/x-icon" href="/assets/favicon.ico">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- DataTables CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap4.min.css">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    <!-- DataTables JavaScript -->
    <script type="text/javascript" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap4.min.js"></script>
</head>
<body>

<div class="container mt-4">
    <h1 class="text-center ">PetsNClaws Orders List</h1>
    <table id="myDataTable" class="table table-bordered table-responsive-sm text-center ">
        <thead>
            <tr>
                <th>ID</th>
                <th>Customer</th>
                <th>Address</th>
                <th>Total Price</th>
                <th>Delivery</th>
                <th>Order date</th>
                <th>isReceived</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
       {% for order in orders %}
            <tr>
                <td>
                    {{order.order_id}}
                </td>
                <td>
                    {{order.customer}}
                </td>
                <td>
                    {{order.address}}
                </td>
                <td>
                    ${{order.total_price}}
                </td>
                <td>
                    {% if  order.delivery %}
                        ${{order.delivery}}
                    {% else %}
                        -
                    {% endif %}
                </td>

                <td>
                    {{order.order_date}}
                </td>
                <td class="text-center">
                    <input type="checkbox" {% if order.isReceived %}checked{% endif %} disabled>
                </td>
                <td>
                    <div class="form-group">
                    <a href="/cart/orders/{{order.order_id}}/" class="btn btn-sm btn-primary">Details</a>
                    </div>
                    <div>
                    <a href="/cart/orders/{{order.order_id}}/received/" class="btn btn-sm btn-success">Received</a>
                    </div>
                </td>
            </tr>
       {% endfor %}
        </tbody>
    </table>
</div>

<script>
$(document).ready(function() {
    // Initialize DataTable
    $('#myDataTable').DataTable({
        // Your DataTable options go here
        // For example:
        "paging": true,
        "ordering": true,
        "info": true
    });

    // Add data to DataTable dynamically
    var table = $('#myDataTable').DataTable();
});
</script>

</body>
</html>

cart/templates/view_cart.html
{% extends 'layout.html' %}



{% block title %} My Cart {% endblock %}




{% block links %} 
<li class="nav-item ">
  <a class="nav-link " href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
  </li>

  <li class="nav-item">
  <a class="nav-link" href="{% url 'home:products' %}">Products</a>
  </li>
  {% comment %} <li class="nav-item">
  <a class="nav-link" href="/shop/customize">customize</a>
  </li>
{% endcomment %}
  <li class="nav-item">
  <a class="nav-link" href="{% url 'home:contactUs' %}">Contact Us</a>
  </li>
  
{% endblock %}

{% block links1 %} 
<li class="nav-item ">
  <a class="nav-link " href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
  </li>

  <li class="nav-item">
  <a class="nav-link" href="{% url 'home:products' %}">Products</a>
  </li>
  {% comment %} <li class="nav-item">
  <a class="nav-link" href="/shop/customize">customize</a>
  </li>
{% endcomment %}
  <li class="nav-item">
  <a class="nav-link" href="{% url 'home:contactUs' %}">Contact Us</a>
  </li>
  
{% endblock %}


{% block main %} 


<div class="container">
    <h2 class="title-sell">My Cart</h2>

   {% if cart|length > 0 %}
   

    <div class="row">
      <div class="col-lg-6">
        <form action="/cart/empty/" method="POST"> 
          {% csrf_token %}
          <button class="form-group btn btn-cart ">
            Clear Cart
            <i class="fa fa-times" aria-hidden="true"></i>
          </button>
        </form>
      </div>
    </div>
    
<div class="shopping-cart">

  <div class="column-labels">
   
    <label class="product-image">image</label>
    <label class="product-details">product</label>
    <label class="product-price">price</label>
    <label class="product-quantity">qty</label>
    <label class="product-removal">remove</label>
    <label class="product-line-price">total</label>
  </div>

    {% for prod in cart %}
    
  
        <div class="product">
          <div class="product-image mt-2">
            <img src="{{prod.image}}" class="rounded-circle" alt="prod_{{prod.name}}">
          </div>
          <div class="product-details mt-md-0 mt-3">
            <div class="product-title h5">{{prod.name}} </div>
            {% comment %} <p class="product-description">{{prod.description}} </p> {% endcomment %}
          </div>
          <div class="product-price">{{settings.currency}}{{prod.price}} </div>
          <div class="product-quantity">
            {% comment %} <input type="text" value="{{prod.qty}}" class="text-center" readonly> {% endcomment %}
            x {{prod.qty}}
          </div>
          <div class="product-removal">
            <a href="/cart/delete/{{ forloop.counter }}/">
              <i class="fas fa-trash green"></i>
            </a>
          </div>
          <div class="product-line-price">{{settings.currency}}{{prod.total_price}} </div>
          
        </div>
    {% endfor %}



  <div class="totals">
    <div class="totals-item h5">
      <label class="">Total</label>
      <div class="totals-value" id="cart-subtotal">{{settings.currency}}{{total_price}} </div>
    </div>
  </div>

</div>

  <div class="row justify-content-center">
    <div class="col-lg-3">
      <a class="btn btn-outline float-right btn-block form-group"href="{% url 'home:products' %}">
        Continue Shopping 
        <i class="fa fa-shopping-cart green-icon" aria-hidden="true"></i>
      </a>
    </div>
    <div class="col-lg-3">
        <a class="btn btn-cart btn-block form-group" href="{% url 'cart:checkout' %}" >
          Checkout
          &nbsp;
          <i class="fa fa-credit-card" aria-hidden="true"></i>
        </a>
    </div>
  </div>
  
  {% else %}
  <div class="empty-cart text-center">
   <img src="/assets/empty-cart.png"  class="img-fluid" alt="empty_cart">
   <h3>Empty cart</h3>
   <p>Add something to make me happy :)</p>
   <a class="btn btn-outline" href="{% url 'home:products' %}">Go Shopping</a>
</div>
  {% endif %}
  <br>

<br>
    
</div>


{% endblock %}